### ISSUE TITLE
Magically install pprof 

### ISSUE THREAD

**Issue by wlandau** [r-prof/proffer#11]
## Prework

- [x] Read and abide by `proffer`'s [code of conduct](https://github.com/r-prof/proffer/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/r-prof/proffer/issues), both open and closed.

## Description

From @rpodcast, `blogdown` has `install_hugo()`, and [Hugo](https://github.com/gohugoio/hugo) is written in Go. `proffer` should emulate this with an `install_pprof()` function to install [`pprof`](https://github.com/google/pprof).

**Comment by krlmlr** [comment]
As a (permanent?) stop-gap, a `dr_proffer()` might help troubleshooting installations.

**Comment by krlmlr** [comment]
What's the reason that the `pprof_path` environment variable is lowercase? AFAIK the convention is to use uppercase.

Can we change to `PROFFER_PPROF_PATH` (and also support `PROFFER_GO_BIN_PATH` and `PROFFER_GRAPHVIZ_PATH`)?

**Comment by krlmlr** [comment]
Do you mind a dependency on {cli} for the installation helper?

**Comment by wlandau** [comment]
> Can we change to PROFFER_PPROF_PATH 

Sure. As of https://github.com/r-prof/proffer/commit/6f442c7084e549934bcb8e13835b34de0db97961, `proffer` looks for `PROFFER_PPROF_PATH` first and then `pprof_path`.

> (and also support PROFFER_GO_BIN_PATH and PROFFER_GRAPHVIZ_PATH)?

`PROFFER_GO_BIN_PATH` sounds reasonable. Would `PROFFER_GRAPHVIZ_PATH` help `pprof` find Graphviz? I thought it needed to be in `PATH`.

> Do you mind a dependency on {cli} for the installation helper?

That's fine with me, seems minor compared to the non-R dependencies.

**Comment by krlmlr** [comment]
We could prepend `$PROFFER_GRAPHVIZ_PATH` to `$PATH` before launching `pprof`, this makes sure that everything can be found.

**Comment by wlandau** [comment]
Are you thinking along those lines for `PROFFER_GO_BIN_PATH`? Seems like [this line](https://github.com/r-prof/proffer/blob/dea59aeab4bac08077c79417b302863ee5e30d94/R/troubleshoot.R#L99) needs Go to be in the path.

**Comment by krlmlr** [comment]
For `go`, we can use `file.path(Sys.getenv("PROFFER_GO_BIN_PATH"), "go")` and use `Sys.which("go")` as fallback. For `graphviz`, we check `Sys.which("dot")` (or whatever is necessary), and if not available, run the code with:

```r
with_envvar(c(PATH = paste0(Sys.getenv("PROFFER_GRAPHVIZ_BIN_PATH"), .Platform$path.sep, Sys.getenv("PATH"))), ...)
```

**Comment by wlandau** [comment]
I think #11 introduced similar enough logic, given that the environment variables point to the executables instead of the `bin/` folders. I made this clearer in a7188ae03db19e65787fe6d07b7b046af006591c by changing `PROFFER_GO_BIN_PATH` to `PROFFER_GO_PATH` and keeping `PROFFER_GRAPHVIZ_PATH` as is.

**Comment by wlandau** [comment]
From https://github.com/google/pprof/issues/364#issuecomment-383395712, we might be okay if we can just install Go and Graphviz. Functions `install_go()` and `install_graphviz()`, if we can implement them, are worth a shot.
