### ISSUE TITLE
Remove AppVeyor 

### ISSUE THREAD

**Issue by wlandau** [r-prof/proffer#24]
## Prework

- [x] Read and abide by `proffer`'s [code of conduct](https://github.com/r-prof/proffer/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/r-prof/proffer/issues), both open and closed.

## Description

I have enabled GitHub Actions for `proffer`, and because it covers Windows, I would prefer to move away from AppVeyor. I deleted the `appveyor.yml` file and deleted `proffer` at appveyor.com, but GitHub still thinks AppVeyor is part of the CI.

![Screen Shot 2020-05-19 at 8 50 29 AM](https://user-images.githubusercontent.com/1580860/82328440-e050b900-99ad-11ea-9286-7d426a8984f1.png)

It looks like AppVeyor is still under GitHub Integrations, and I see no way to remove it. This may require `r-prof` org admin privileges. @krlmlr, would you see if you can remove it when you get a chance?

![Screen Shot 2020-05-19 at 8 48 41 AM](https://user-images.githubusercontent.com/1580860/82328488-f6f71000-99ad-11ea-8b69-831dfe6315bc.png)

**Comment by krlmlr** [comment]
Deleted on AppVeyor.

**Comment by wlandau** [comment]
Looks to have worked, thanks!
