### ISSUE TITLE
Do not use callr::r_bg, use processx::process instead

### ISSUE THREAD

**Issue by gaborcsardi** [r-prof/proffer#5]
## Prework

- [x] Read and abide by `proffer`'s [code of conduct](https://github.com/r-prof/proffer/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/r-prof/proffer/issues), both open and closed.

## Description

I might be missing something, but what is the point of using `r_bg()` to start up a background R process which then just starts another process via `system2()`? Then you'll get processes R -> background R -> shell -> pprof.

If you use `processx::process`, then you get R -> pprof. Isn't that better?

**Comment by wlandau** [comment]
I agree, thanks for the tip. Now implemented.
